apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ .Release.Name }}-admission
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ .Release.Name }}-certificate
webhooks:
- name: {{ .Release.Name }}.{{ .Release.Namespace }}.stater.com
  clientConfig:
    service:
      name: {{ .Release.Name }}
      namespace: {{ .Release.Namespace }}
      path: "/validate"
  rules:
    - operations: ["CREATE","UPDATE"]
      apiGroups: ["external-secrets.io"]
      apiVersions: ["v1alpha1"]
      resources: ["externalsecrets"]
  failurePolicy: Fail
  matchPolicy: Equivalent
  sideEffects: None
  admissionReviewVersions: ["v1"]
---
